const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"成品检验类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryChengpinjianyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"来料检验类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryLailiaojianyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"抽样标准类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryChouyangbiaozhun"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"出货检验类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryChuhuojianyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGonggao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"检验工种管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJianyangongzhong"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"检验项目管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJianyanxiangmu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"检验仪器管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJianyanyiqi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"检验中心管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJianyanzhongxin"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"控制图初始化类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryKongzhituchushihua"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"质量等级管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZhiliangdengji"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"缺陷等级管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryQuexiandengji"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"缺陷原因类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryQuexianyuanyin"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"制成检验类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZhichengjianyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"立方图输出类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryLifangtu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"直方图输出类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZhifangtu"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"抽样标准管理",
                        "menuJump":"列表",
                        "tableName":"chouyangbiaozhun"
                    }
                ],
                "menu":"抽样标准管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "报表",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"来料检验管理",
                        "menuJump":"列表",
                        "tableName":"lailiaojianyan"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "报表",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"制成检验管理",
                        "menuJump":"列表",
                        "tableName":"zhichengjianyan"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "报表",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"成品检验管理",
                        "menuJump":"列表",
                        "tableName":"chengpinjianyan"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "报表",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"出货检验管理",
                        "menuJump":"列表",
                        "tableName":"chuhuojianyan"
                    }
                ],
                "menu":"质量检测管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"控制图初始化管理",
                        "menuJump":"列表",
                        "tableName":"kongzhituchushihua"
                    }
                ],
                "menu":"质量控制管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"输出直方图管理",
                        "menuJump":"列表",
                        "tableName":"zhifangtu"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"输出立方图管理",
                        "menuJump":"列表",
                        "tableName":"lifangtu"
                    }
                ],
                "menu":"质量分析管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"工作人员管理",
                        "menuJump":"列表",
                        "tableName":"gongzuorenyuan"
                    }
                ],
                "menu":"工作人员管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"抽样标准管理",
                        "menuJump":"列表",
                        "tableName":"chouyangbiaozhun"
                    }
                ],
                "menu":"抽样标准管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"来料检验管理",
                        "menuJump":"列表",
                        "tableName":"lailiaojianyan"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"制成检验管理",
                        "menuJump":"列表",
                        "tableName":"zhichengjianyan"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"成品检验管理",
                        "menuJump":"列表",
                        "tableName":"chengpinjianyan"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"出货检验管理",
                        "menuJump":"列表",
                        "tableName":"chuhuojianyan"
                    }
                ],
                "menu":"质量检测管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"控制图初始化管理",
                        "menuJump":"列表",
                        "tableName":"kongzhituchushihua"
                    }
                ],
                "menu":"质量控制管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"输出直方图管理",
                        "menuJump":"列表",
                        "tableName":"zhifangtu"
                    }
					,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"输出立方图管理",
                        "menuJump":"列表",
                        "tableName":"lifangtu"
                    }
                ],
                "menu":"质量分析管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"工作人员",
        "tableName":"gongzuorenyuan"
    }
]
    }
}
export default menu;
